[tool.poetry]
name = "flask-project"
version = "0.1.0"
description = ""
authors = ["Mark Berridge <mark.berridge@digital.justice.gov.uk>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
Metaphone = "^0.6"
numpy = "^1.21.2"
python-dateutil = "^2.8.2"
pytz = "^2021.1"
six = "^1.16.0"
textdistance = "^4.2.1"
aws-lambda-powertools = "^1.20.2"
boto3 = "^1.18.36"
pandas = "^1.3.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^3.9.2"
pytest-cov = "^2.12.1"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"