version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@7.1.0
  jira: circleci/jira@1.3.1

executors:
  builder:
    docker:
      - image: cimg/python:3.11.1
    working_directory: ~/app


jobs:
  build:
    executor: builder
    steps:
      - checkout
      - run: poetry install
      - run: poetry run pytest
workflows:
  build-test-and-deploy:
    jobs:
      - build:
          context:
          - hmpps-common-vars
          filters:
            tags:
              ignore: /.*/
      - hmpps/build_docker:
          name: build_docker
          context:
            - hmpps-common-vars
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-person-record-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          context:
            - hmpps-common-vars
            - hmpps-person-record-prod
          requires:
            - request-prod-approval
