version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@5.1.0
  jira: circleci/jira@1.3.1
  slack: circleci/slack@4.10.1

executors:
  builder:
    docker:
      - image: cimg/python:3.9.13
    working_directory: ~/app


jobs:
  build:
    executor: builder
    steps:
      - checkout
      - run: poetry install
      - run: poetry run pytest
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/build_docker:
          name: build_docker
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - PIC-2145
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context:
            - hmpps-common-vars
            - court-probation-live-dev
          filters:
            branches:
              only:
                - main
                - PIC-2145
          requires:
            - build_docker
