---
generic-service:
  replicaCount: 1

  scheduledDowntime:
    enabled: true

  ingress:
    host: hmpps-person-match-score-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-person-record-dev-cert-secret

generic-prometheus-alerts:
  businessHoursOnly: true
