name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "34 7 * * 1-5" # Every weekday

permissions:
  packages: read
  actions: read
  contents: read
  security-events: write

jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@trivy-scan-permissions
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
